package com.innominds.todo.entity;

import java.io.Serializable;
import java.time.Instant;

import org.springframework.data.annotation.CreatedBy;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.Id;
import org.springframework.data.annotation.LastModifiedBy;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.annotation.Version;

/**
 * Base entity
 *
 * 
 */
public abstract class BaseEntityMongoDB implements Serializable {

	/** serial version UID */
	private static final long serialVersionUID = 1L;

	public static final String FIELD_ID = "id";

	/** The Constant FIELD_DELIMITER_MONGODB. */
	public static final String FIELD_DELIMITER_MONGODB = ".";

	/** The Constant FIELD_CREATIONDATE. */
	public static final String FIELD_CREATIONDATE = "creationDate";

	/** The Constant FIELD_LAST_MODIFIED_DATE. */
	public static final String FIELD_LAST_MODIFIED_DATE = "lastModifiedDate";

	/** The Constant FIELD_VERSION. */
	public static final String FIELD_VERSION = "version";

	/** primary key as GUID - generated by mongoDB */
	@Id
	// @GeneratedValue(strategy = GenerationType.IDENTITY)
	private String id;

	/** The created by. */
	@CreatedBy
	private String createdBy;

	/** The last modified by. */
	@LastModifiedBy
	private String lastModifiedBy;

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	/** The creation date. */
	@CreatedDate
	private Instant creationDate;

	/** The last modified date. */
	@LastModifiedDate
	private Instant lastModifiedDate;

	/** The version. */
	@Version
	private long version;

	/**
	 * Gets the created by.
	 *
	 * @return the created by
	 */
	public String getCreatedBy() {
		return createdBy;
	}

	/**
	 * Sets the created by.
	 *
	 * @param createdBy the new created by
	 */
	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	/**
	 * Gets the last modified by.
	 *
	 * @return the last modified by
	 */
	public String getLastModifiedBy() {
		return lastModifiedBy;
	}

	/**
	 * Sets the last modified by.
	 *
	 * @param lastModifiedBy the new last modified by
	 */
	public void setLastModifiedBy(String lastModifiedBy) {
		this.lastModifiedBy = lastModifiedBy;
	}

	/**
	 * Gets the creation date.
	 *
	 * @return the creation date
	 */
	public Instant getCreationDate() {
		return creationDate;
	}

	/**
	 * Sets the creation date.
	 *
	 * @param instant the new creation date
	 */
	public void setCreationDate(Instant instant) {
		this.creationDate = instant;
	}

	/**
	 * Gets the last modified date.
	 *
	 * @return the last modified date
	 */
	public Instant getLastModifiedDate() {
		return lastModifiedDate;
	}

	/**
	 * Sets the last modified date.
	 *
	 * @param lastModifiedDate the new last modified date
	 */
	public void setLastModifiedDate(Instant lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	/**
	 * Gets the version.
	 *
	 * @return the version
	 */
	public long getVersion() {
		return version;
	}

	/**
	 * Sets the version.
	 *
	 * @param version the new version
	 */
	public void setVersion(long version) {
		this.version = version;
	}
}
